CREATE TABLE aircon (
	`ApplStandard` VARCHAR(110) NOT NULL, 
	`MEPSComp` VARCHAR(18), 
	`N-Standard` VARCHAR(32), 
	`Model Name` VARCHAR(41), 
	`Model_No` VARCHAR(92) NOT NULL, 
	avg_pwr_standby_mode VARCHAR(32), 
	`Brand` VARCHAR(33), 
	`C-Dehumid_Rated` FLOAT, 
	`Configuration1` VARCHAR(10) NOT NULL, 
	`Configuration2` VARCHAR(27) NOT NULL, 
	`Configuration2-unitmount` VARCHAR(13), 
	`Configuration3_Sink` VARCHAR(13), 
	`Configuration3_Source` VARCHAR(18), 
	`Country` VARCHAR(47), 
	`C-Power_Inp_Rated` VARCHAR(14), 
	`C-Sens_Cool_Rated` VARCHAR(10), 
	`C-Total Cool Rated` FLOAT, 
	`Depth` FLOAT, 
	`H2_COP` FLOAT, 
	`H2_HeatPwrCapacity` FLOAT, 
	`H2_HeatPwrInput` FLOAT, 
	`Height` FLOAT, 
	`H-Power_Inp_Rated` FLOAT, 
	`H-Total Heat Rated` FLOAT, 
	`indoorType` VARCHAR(21), 
	`EERtestAvg` VARCHAR(18), 
	`COPtestAvg` VARCHAR(18), 
	`Invert` VARCHAR(6), 
	`Setting_cool` VARCHAR(10), 
	`Setting_heat` VARCHAR(5), 
	`Pnoc` FLOAT, 
	`Pnoh` FLOAT, 
	`VSCP_EER50` FLOAT, 
	`VSCP_COP50` FLOAT, 
	eermepslev FLOAT, 
	`TestedOutputEER` FLOAT, 
	`TestedOutputCOP` FLOAT, 
	`AnnualOutputEER` FLOAT, 
	`AnnualOutputCOP` FLOAT, 
	`PL_EERMEPS` FLOAT, 
	`PL_COPMEPS` FLOAT, 
	sri2010_cool FLOAT, 
	sri2010_heat FLOAT, 
	`Star2010_Cool` FLOAT, 
	`Star2010_Heat` FLOAT, 
	outdoortype VARCHAR(21), 
	`Phase` VARCHAR(18), 
	`Refrigerant` VARCHAR(18), 
	`Sold_in` VARCHAR(32), 
	`Submit_ID` VARCHAR(26), 
	`ExpDate` VARCHAR(26), 
	`GrandDate` VARCHAR(10), 
	`SubmitStatus` VARCHAR(10), 
	`Type` VARCHAR(13), 
	`Width` VARCHAR(13), 
	`Product Class` VARCHAR(13), 
	`Demand Response 1` VARCHAR(8), 
	`Demand Response 2` VARCHAR(8), 
	`Demand Response 4` BOOL, 
	`Demand Response 5` BOOL, 
	`Demand Response 6` BOOL, 
	`Demand Response 7` BOOL, 
	`PartNumber` VARCHAR(40), 
	`EER` VARCHAR(11), 
	`Availability Status` VARCHAR(11), 
	star2000_cool VARCHAR(11), 
	star2000_heat VARCHAR(11), 
	`Product Website` VARCHAR(40), 
	`Representative Brand URL` VARCHAR(83), 
	`Star Image Large` VARCHAR(99), 
	`Star Image Small` VARCHAR(99), 
	CHECK (`Demand Response 4` IN (0, 1)), 
	CHECK (`Demand Response 5` IN (0, 1)), 
	CHECK (`Demand Response 6` IN (0, 1)), 
	CHECK (`Demand Response 7` IN (0, 1))
);
